### ISSUE TITLE
Project scope definition

### ISSUE THREAD

**Issue by guilhermespopolin** [lemes/redux-shelf#2]
In order to guarantee correct focus on our goals during all library development process, it ncessary that we establish its scope first, by responding the follow question: "What specif problem we wanna solve?"

**Comment by lemes** [comment]
To reduce boilerplate for dealing with reducers/action/connect of an application entities (models or types, whatever you named it). 

## ducks
### entities
Handle entity data in a hash map object
- set
- update *
- remove **

(*) optional selector
(**) selector required

### communication
Handle any not-yet-complete actions for your entities
- add *
- remove *
- update *
(*) optional selector

**Comment by lemes** [comment]
What should `fail` do when no error is provided?

**Comment by lemes** [comment]
The `entities` reducer is not prepared to handle ids and content internally. Let's work on that for the next milestone.
