### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by guilhermespopolin** [lemes/redux-shelf#3]
Library public API definition.

**Comment by lemes** [comment]
```
// status: STARTING or FAILED

mapStateToProps({
  communication
}, { userId }) => {
  communication.of('users').error; // (undefined|error)
  communication.of('users', userId).loading; // (true|false)
}

// communication: {
//   {type[:selector]}: { status, [error] }
// }

mapStateToProps({
  entities
}, { userId }) => {
  const ids = entities.{idsOf,of}('users');
  const content = entities.{contentOf,of}('users', userId);
}]`

**Comment by renerbaffa** [comment]
We decided to take the following approach to use:
```// ids and content
set('users', {
  ids: [1, 2],
  content: {
    1: { id: "1", name: "Paul" },
    2: { id: "2", name: "Nicole" }
  },
});```

**Comment by renerbaffa** [comment]
We decided to provide a `normalize` to convert structure to `ids` and `content`

**Comment by guilhermespopolin** [comment]
@renerbaffa so is this the correct approach:

```javascript
function
```

**Comment by renerbaffa** [comment]
Eventually, the developer should provide all the schemas for the application and when using an action system will match the type with schema.

**Comment by renerbaffa** [comment]
@guilhermespopolin yes to be more assertive, something like this:
```
// array of objects default
set('users', [{ id: "1", name: "Paul" }, { id: "2", name: "Nicole" }]);

// array of objects with option key
set('users', normalize(
  [{ staffId: "1", name: "Paul" }, { staffId: "2", name: "Nicole" }],
  'staffId',
));
```

But if we implement schemas, a normalize becomes unnecessary.
Providing a normalize will be valid only for the first versions where we accept only the ids and content pattern.

**Comment by guilhermespopolin** [comment]
@lemes 
Why this cannot return `STARTING`? I mean, the version of `of` method without the entity identifier gets the communication state about entity, and I think `STARTING` is a valid status for this case, in order to represent an in progress request to an external service.

**Comment by lemes** [comment]
@guilhermespopolin in the end what we want it whether it is `starting` or not, therefore, `loading: true|false`.
